name: Main

on:
  push:
  pull_request:
    branches-ignore:
      - 'temp*'
      - 'tmp*'
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ "14", "16", "18" ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build and unit tests
        run: |
          npm run build --if-present
          npm run test

      - name: browser tests
        run: |
          npm run browser-tests
